class_name ItemDB
extends Node

const ITEMS = [
	{
		"name": "（空）",
		"description": "空道具，你不应该看到我。",
		"money": 0,
		"exp": 999,
		"health": 999,
		"attack": 999,
		"defend": 999,
	},
	{
		"name": "红玫瑰",
		"description": "娇艳欲滴的鲜红玫瑰，但隐藏着锋利的毒刺。",
		"money": 50,
		"exp": 30,
		"health": -30,
		"attack": 0,
		"defend": 0,
	},
	{
		"name": "花蘑菇",
		"description": "疗伤用的菌类。",
		"money": 40,
		"exp": 0,
		"health": 40,
		"attack": 0,
		"defend": 0,
	},
	{
		"name": "止血草",
		"description": "止血疗伤的草药。",
		"money": 60,
		"exp": 0,
		"health": 80,
		"attack": 0,
		"defend": 0,
	},
	{
		"name": "还魂草",
		"description": "非常有效的药物，拥有起死回生的功效。",
		"money": 120,
		"exp": 0,
		"health": 150,
		"attack": 0,
		"defend": 0,
	},
	{
		"name": "粉骷髅",
		"description": "邪恶的象征，需要涂上正义的鲜血才能发挥它的功效。",
		"money": 200,
		"exp": 50,
		"health": -50,
		"attack": 1,
		"defend": 1,
	},
	{
		"name": "长拳拳谱",
		"description": "一本普通的拳谱。",
		"money": 400,
		"exp": 50,
		"health": 0,
		"attack": 2,
		"defend": 2,
	},
	{
		"name": "重剑",
		"description": "笨重的武器，但具有相当大的杀伤力！",
		"money": 200,
		"exp": 0,
		"health": 0,
		"attack": 4,
		"defend": 4,
	},
	{
		"name": "圣剑",
		"description": "威力无比的宝物，相传为剑圣当年使用的兵器。",
		"money": 4000,
		"exp": 0,
		"health": 0,
		"attack": 10,
		"defend": 10,
	},
	{
		"name": "匕首",
		"description": "短身的刀具，短小但很合手，适合初学者用，但攻击力偏小……",
		"money": 100,
		"exp": 0,
		"health": 0,
		"attack": 1,
		"defend": 0,
	},
	{
		"name": "凝霜剑",
		"description": "长刃刀，在三伏天会在剑身上凝结水滴。",
		"money": 360,
		"exp": 0,
		"health": 0,
		"attack": 4,
		"defend": 0,
	},
	{
		"name": "古文明盔甲",
		"description": "迷的古代文明的遗迹挖掘出的盔甲，在胸前刻有「中华人民共合国制造」的字样。",
		"money": 360,
		"exp": 0,
		"health": 0,
		"attack": 4,
		"defend": 0,
	},
	{
		"name": "凝霜剑",
		"description": "长刃刀，在三伏天会在剑身上凝结水滴。",
		"money": 360,
		"exp": 0,
		"health": 0,
		"attack": 4,
		"defend": 0,
	},
	{
		"name": "皮甲",
		"description": "用皮革制造成的战甲，能够抵御刀箭的伤害。",
		"money": 100,
		"exp": 0,
		"health": 0,
		"attack": 0,
		"defend": 1,
	},
	{
		"name": "红色药瓶",
		"description": "未知的药物，未知的效果……",
		"money": 500,
		"exp": 0,
		"health": 100,
		"attack": 3,
		"defend": 3,
	},
	{
		"name": "药瓶",
		"description": "装有药物的玻璃瓶，但没有标签，所以喝下后有50%的可能中毒……",
		"money": 200,
		"exp": 0,
		"health": 999,
		"attack": 0,
		"defend": 0,
	},
]
